apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluemap-external
  labels:
    app: bluemap
  annotations:
    kubernetes.io/ingress.class: nginx-external
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx-external
  rules:
    - host: map.kirkoc.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bluemap
                port:
                  number: 8100
  tls:
    - secretName: bluemap-external-tls
      hosts:
        - map.kirkoc.net