apiVersion: v1
kind: Service
metadata:
  name: bluemap
  labels:
    app: bluemap
spec:
  ports:
    - protocol: TCP
      port: 8100
      targetPort: http
      name: http
  selector:
    app: bluemap