apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-external
  labels:
    app: keycloak
  annotations:
    kubernetes.io/ingress.class: nginx-external
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx-external
  rules:
    - host: auth.kirkoc.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
  tls:
    - secretName: keycloak-external-tls
      hosts:
        - auth.kirkoc.net
